import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { Report } from '../models/Report';
import { logger } from '../utils/logger';

const REPORTS_DIR = path.join(process.cwd(), 'reports');

// Ensure reports directory exists
if (!fs.existsSync(REPORTS_DIR)) {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
}

export async function generatePDF(reportId: string): Promise<string> {
  const report = await Report.findById(reportId);
  if (!report) throw new Error(`Report ${reportId} not found`);

  const filePath = path.join(REPORTS_DIR, `${reportId}.pdf`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);

    doc.pipe(stream as any);

    // Header
    doc
      .fontSize(24)
      .fillColor('#58C46B')
      .text('DevPulse', { align: 'center' })
      .fontSize(14)
      .fillColor('#333')
      .text(report.title, { align: 'center' })
      .moveDown();

    doc
      .fontSize(10)
      .fillColor('#666')
      .text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' })
      .text(`Type: ${report.type}`, { align: 'center' })
      .moveDown(2);

    // Content
    doc.fontSize(12).fillColor('#333');

    if (report.data) {
      const data = report.data as Record<string, unknown>;
      for (const [key, value] of Object.entries(data)) {
        if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
          doc
            .fontSize(11)
            .fillColor('#444')
            .text(formatKey(key) + ':', { continued: false })
            .fontSize(10)
            .fillColor('#666')
            .text(String(value))
            .moveDown(0.5);
        } else if (Array.isArray(value)) {
          doc
            .fontSize(11)
            .fillColor('#444')
            .text(formatKey(key) + ':')
            .fontSize(10)
            .fillColor('#666');

          for (const item of value.slice(0, 10)) {
            doc.text(`  • ${String(item)}`);
          }
          doc.moveDown(0.5);
        }
      }
    }

    // Footer
    doc
      .moveDown(2)
      .fontSize(8)
      .fillColor('#999')
      .text('Generated by DevPulse — GitHub Analytics & Career Insights Platform', {
        align: 'center',
      });

    doc.end();

    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

function formatKey(key: string): string {
  return key.replace(/([A-Z])/g, ' $1').replace(/^./, (s) => s.toUpperCase());
}

export function getReportPath(reportId: string): string | null {
  const filePath = path.join(REPORTS_DIR, `${reportId}.pdf`);
  return fs.existsSync(filePath) ? filePath : null;
}

export async function buildReportData(
  userId: string,
  reportType: string
): Promise<Record<string, unknown>> {
  const { User } = await import('../models/User');
  const { Repository } = await import('../models/Repository');
  const { fetchGitHubRepos, mapGitHubRepo } = await import('./github.service');
  const { calcHealthScore } = await import('./score.service');
  const { decrypt } = await import('../utils/encryption');

  const user = await User.findById(userId);
  if (!user) return {};

  let repos = await Repository.find({ userId }).sort({ stars: -1 }).limit(10).lean();

  // Self-healing: if database doesn't have repos mapped, fetch live from GitHub
  if (repos.length === 0 && user.githubAccessToken) {
    try {
      const token = decrypt(user.githubAccessToken);
      if (token && token !== 'mock_github_token_for_seeding') {
        const ghRepos = await fetchGitHubRepos(token, user.username);
        const repoDocs = ghRepos.map((r) => {
          const mapped = mapGitHubRepo(r);
          const healthScore = calcHealthScore({
            stars: mapped.stars,
            forks: mapped.forks,
            issues: mapped.issues,
            commits: 10,
            contributors: 1,
            description: mapped.description,
            topics: mapped.topics,
            lastUpdated: mapped.lastUpdated,
          });
          return {
            userId,
            ...mapped,
            commits: 10,
            contributors: 1,
            healthScore,
          };
        });

        if (repoDocs.length > 0) {
          await Repository.insertMany(repoDocs);
          repos = await Repository.find({ userId }).sort({ stars: -1 }).limit(10).lean() as any;
        }
      }
    } catch (err: any) {
      logger.warn(`Report builder failed live fetch: ${err.message}`);
    }
  }

  const matchesFrontend = repos.some((r) => r.language === 'TypeScript' || r.language === 'JavaScript');

  switch (reportType) {
    case 'Career Analysis':
      return {
        username: user.username,
        totalContributions: user.contributions,
        streak: `${user.streak} days`,
        topLanguages: [...new Set(repos.map((r) => r.language).filter(Boolean))].join(', '),
        topRepos: repos.map((r) => `${r.name} (⭐${r.stars})`),
        recommendations: matchesFrontend
          ? 'Based on your TypeScript/JavaScript core, you are well-positioned for Frontend or Full Stack engineering roles. Focus on mastering Next.js, component design patterns, and testing suites.'
          : 'Your portfolio highlights strong backend language proficiency. We recommend expanding your knowledge of system design, database indexing, and container orchestration (Docker/Kubernetes).',
      };

    case 'Repository Health':
      return {
        username: user.username,
        totalRepos: user.publicRepos,
        averageHealthScore: repos.length
          ? Math.round(repos.reduce((a, r) => a + r.healthScore, 0) / repos.length)
          : 0,
        topRepos: repos.map((r) => `${r.name}: ${r.healthScore}% health`),
        totalStars: repos.reduce((a, r) => a + r.stars, 0),
        totalForks: repos.reduce((a, r) => a + r.forks, 0),
      };

    case 'Skills Assessment':
      return {
        username: user.username,
        languages: [...new Set(repos.map((r) => r.language).filter(Boolean))],
        topics: [...new Set(repos.flatMap((r) => r.topics))].slice(0, 20),
        contributions: user.contributions,
        streak: `${user.streak} days`,
        score: user.leaderboardScore,
        recommendedSkillsToAcquire: matchesFrontend
          ? ['Next.js App Router', 'React Testing Library', 'GraphQL API Design', 'Tailwind CSS']
          : ['Docker Containers', 'Microservices Architecture', 'PostgreSQL Query Optimizations', 'Redis Caching Layer'],
      };

    case 'Profile Overview':
    default:
      return {
        username: user.username,
        name: user.name ?? user.username,
        bio: user.bio ?? '',
        location: user.location ?? '',
        company: user.company ?? '',
        followers: user.followers,
        following: user.following,
        publicRepos: user.publicRepos,
        contributions: user.contributions,
        streak: `${user.streak} days`,
        leaderboardScore: user.leaderboardScore,
      };
  }
}

export async function markReportFailed(reportId: string, error: string): Promise<void> {
  await Report.findByIdAndUpdate(reportId, {
    status: 'failed',
    error,
  });
  logger.error(`Report ${reportId} failed:`, error);
}
